### ISSUE TITLE
调查FileDependency::isExpired抛出错误的原因

### ISSUE THREAD

**Issue by rpuboh** [TopRealm/MediaWiki#13]
在profiler工具excimer生成的火焰图中可见`FileDependency::isExpired`会调用`MWExceptionHandler::handleError`，这应该说明该函数执行期间抛出了php error。error handler消耗的时间在毫秒粒度的火焰图中清晰可见，其性能影响已通过 https://github.com/TopRealm/MediaWiki/commit/9d1e81c983ba56344f7ffd22d49991f0bb7b814c 部分缓解，但正常情况下不应需要执行error handler，遂应继续调查原因。

可尝试这样的排查步骤：
1. 注释 [includes/language/dependency/FileDependency.php](https://github.com/TopRealm/MediaWiki/blob/078e02d/includes/language/dependency/FileDependency.php#L74) 的第75、77行（调用`AtEase`包的）
2. 在 LocalSettings.php 配置日志输出 `$wgDebugLogGroups['error'] = '某个文件';`
3. 打开excimer的采样。访问任意页面，观察日志文件是否有内容

如果仍然没有日志输出，检查excimer火焰图中`FileDependency::isExpired`函数的调用栈是否已不再触发error handler。

更多上下文可参考2024-05-14的QQ群聊天记录。

**Comment by ZoruaFox** [comment]
就第一行作出更改后所有i18n文件出现类似异常
```php
Warning: filemtime(): stat failed for /www/wwwroot/MediaWiki/includes/api/i18n/zh.json in /www/wwwroot/MediaWiki/includes/language/dependency/FileDependency.php on line 76
Warning: Cannot modify header information - headers already sent by (output started at /www/wwwroot/MediaWiki/includes/language/dependency/FileDependency.php:76) in /www/wwwroot/MediaWiki/includes/WebResponse.php on line 75
```

**Comment by rpuboh** [comment]
我这儿刚才测试抓取的时候刚好碰到了
![](https://github.com/TopRealm/MediaWiki/assets/168681043/9b659d24-7a8a-41f4-a008-e9d1cd393df9)

或许和默认的语言设置有些关系( https://github.com/TopRealm/MediaWiki/commit/56c353ba5bf22464520305acfbfc26727803516c )。之后检查一下它选取文件的方式

**Comment by rpuboh** [comment]
我认为可以在LocalSettings.php中采用wmf站点使用的配置项`$wgLocalisationCacheConf['manualRecache'] = true;`。参见 https://github.com/wikimedia/operations-mediawiki-config/blob/429ebcf/wmf-config/CommonSettings.php#L530

我怀疑这个问题或许是使用了随请求检查cache的功能就会发生的，wmf自己的部署没有使用此功能所以没有意识到性能问题。设置了`manualRecache`后站长请在升级extension或mediawiki（语言翻译文件有改动）后手动执行`maintenance/rebuildLocalisationCache.php --threads=nn`（应该无需`--force`）。

---
我之后可能会尝试自己搭建一个mediawiki环境复现这个问题，并向上游提出bug report。

可能相关：https://phabricator.wikimedia.org/T152371

**Comment by rpuboh** [comment]
[maintenance/rebuildLocalisationCache.php](https://github.com/wikimedia/mediawiki/blob/1.39.7/maintenance/rebuildLocalisationCache.php#L56) 有一个`--lang`参数，可以考虑指定`en,zh...`来限制缓存的生成范围、节省硬盘空间。不过暂时不知道会不会有别的副作用（如果请求了一个没有缓存的语言估计会报错）。值得一提的是访客可以自行添加如`?uselang=ja`的参数来选择界面语言，尽管本站显然不需要特地支持这种用法。

---
`LCStoreStaticArray`给opcache带来的内存占用可参考讨论 https://phabricator.wikimedia.org/T99740

wmf自己使用一个小脚本 [php7adm](https://wikitech.wikimedia.org/wiki/Application_servers/Runbook#php7adm) 观察opcache和apcu的统计信息。它的实现可以在他们的仓库里找到 [admin/lib.php](https://github.com/wikimedia/operations-puppet/tree/cdda34b/modules/profile/files/mediawiki/php)。可以看到它的原理是调用包括`opcache_get_status`, `apcu_cache_info`, `apcu_sma_info`在内的库函数。

这种PHP探针风格的小PHP脚本应该有现成的，且还带简单的数据可视化。站长如果有调整opcache或apcu内存参数的需要可以找一个来观察。
