### ISSUE TITLE
清理WikiSEO插件设置的过时页面属性

### ISSUE THREAD

**Issue by rpuboh** [TopRealm/MediaWiki#14]
WikiSEO的parser function会保持条目在`page_props`表中设置的SEO相关属性。不删除条目中的`{{#seo}}`标记或者禁用该扩展就无法在不通过其他方式编辑`page_props`表的情况下清除过时的SEO属性。

可考虑通过下列步骤进行清理：
1. 注释 [extensions/WikiSEO/includes/WikiSEO.php](https://github.com/wikimedia/mediawiki-extensions-WikiSEO/blob/3c62401/includes/WikiSEO.php#L474) 的第474行（`fromParserFunction`函数内，功能为从数据库中读取原页面的SEO属性）
2. 通过`action=purge`重新生成受影响页面的parser cache（仅有“有兽焉”条目受影响）

使用`action=info`检查清理是否成功。最后将扩展代码修改还原。

上下文参见2024-06-01的QQ群聊天记录。

**Comment by ZoruaFox** [comment]
已注释并观察到变化。相关更改确认无误后可选择提交至上游，本更改将会在下一次git版本更新时被重置。

**Comment by rpuboh** [comment]
这个行为大概是上游故意如此。可能应该向上游提交功能建议。此后如果还需要清理SEO属性暂时按这里的步骤手动处理吧。
