### ISSUE TITLE
调查file cache未生效的原因

### ISSUE THREAD

**Issue by rpuboh** [TopRealm/MediaWiki#33]
此功能文档见[Manual:File cache](https://www.mediawiki.org/wiki/Manual:File_cache)

目前站点配置中虽然启用了file cache，但测试发现它并未生效 https://github.com/TopRealm/MediaWiki/blob/ad7266313fd7a7106bd192713625d07226e8bae6/LocalSettings.php#L116-L118

可反复执行`curl -v --compressed https://youshou.wiki/wiki/File:Dash.svg | tail`并观察`wgBackendResponseTime`的值来判断响应是来自缓存还是动态生成的。动态生成的页面生成用时恰好相等的机会很小。

不过测试时需要注意的是有些页面可能会被腾讯云CDN (EdgeOne)缓存，因此需留意HTTP响应头中`EO-Cache-Status`的值，或者在源站服务器上绕过CDN直连nginx以规避CDN缓存策略的干扰。

---
mediawiki源码中决定是否使用file cache的入口在MediaWiki.php（https://github.com/wikimedia/mediawiki/blob/1.39.8/includes/MediaWiki.php#L879 新版本这块逻辑被refactor到了ActionEntryPoint.php）。调试时建议着重观察此处`HTMLFileCache::useFileCache`函数的返回值，若无异常则观察接下来的if代码块中是否出现了其他错误。

**Comment by ZoruaFox** [comment]
未观测到显著性能影响，暂不修复
